// <auto-generated />
using HotelListing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210921210939_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelListing.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Morocco",
                            ShortName = "MA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "France",
                            ShortName = "FR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United States",
                            ShortName = "USA"
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "8867 Newcastle Street Deerfield Beach, Nice",
                            CountryId = 2,
                            Name = "Twin Keep Hotel & Spa",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Adress = "924 Carson St. Odenton, MD 21113",
                            CountryId = 3,
                            Name = "Regal Mill Resort & Sp",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Adress = "82 Main St. Brownsburg, IN 46112",
                            CountryId = 3,
                            Name = "Mellow Forest Hotel & Spa",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 4,
                            Adress = "7270 Pennsylvania Street Fort Wayne, IN 46804",
                            CountryId = 3,
                            Name = "Pacific Courtyard Hotel & Spa",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 5,
                            Adress = "7583 Railroad Avenue Suite 8 Roselle, Pa",
                            CountryId = 2,
                            Name = "Brass Cosmos Hotel",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 6,
                            Adress = "9 Andover Ave. Warminster, PA 18974",
                            CountryId = 3,
                            Name = "Sunny Emperor Resort & Spa",
                            Rating = 3.8999999999999999
                        },
                        new
                        {
                            Id = 7,
                            Adress = "Hay Riad Street 123, Rabat",
                            CountryId = 1,
                            Name = "Ornate Resort & Spa",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 8,
                            Adress = "444 North Lookout St. Fort Worth, TX 76110",
                            CountryId = 3,
                            Name = "Epitome Hotel",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 9,
                            Adress = "4 Second Ave. Clifton Park, NY 12065",
                            CountryId = 3,
                            Name = "Opportunity Hotel",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 10,
                            Adress = "7614 James Street Largo, FL 33771",
                            CountryId = 3,
                            Name = "Nature Hotel & Spa",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
